package agents

// BuiltinTemplates returns a set of ready-to-use agent templates with sensible defaults.
func BuiltinTemplates() []AgentTemplate {
	// Helper presets for common roles.
	tmpl := []AgentTemplate{
		{
			Name:            "researcher",
			Description:     "Templates for a research-focused agent",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               false,
				AllowBrowser:             false,
				AllowBackgroundSubagents: true,
				MaxMemoryMB:              4096,
				MaxCPUFraction:           0.8,
				TimeoutSeconds:           600,
				MaxConcurrentTasks:       2,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule: ScheduleConfig{
				Cron:              "",
				HeartbeatInterval: 0,
				ActiveHours:       nil,
				JitterSeconds:     0,
				Enabled:           true,
			},
			SystemPromptTemplate: "You are a research assistant. Gather, organize, and summarize information from provided inputs and external sources when allowed.",
		},
		{
			Name:            "coder",
			Description:     "Coding assistant template",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               true,
				AllowBrowser:             false,
				AllowBackgroundSubagents: true,
				MaxMemoryMB:              4096,
				MaxCPUFraction:           0.8,
				TimeoutSeconds:           600,
				MaxConcurrentTasks:       2,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule:      ScheduleConfig{Cron: "", HeartbeatInterval: 0, ActiveHours: nil, JitterSeconds: 0, Enabled: true},
			SystemPromptTemplate: "You are a code assistant. Produce clean, idiomatic Go code and explain design decisions succinctly.",
		},
		{
			Name:            "analyst",
			Description:     "Analyst persona for data interpretation",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               false,
				AllowBrowser:             true,
				AllowBackgroundSubagents: true,
				MaxMemoryMB:              4096,
				MaxCPUFraction:           0.7,
				TimeoutSeconds:           600,
				MaxConcurrentTasks:       2,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule:      ScheduleConfig{Cron: "", HeartbeatInterval: 0, ActiveHours: nil, JitterSeconds: 0, Enabled: true},
			SystemPromptTemplate: "You are an analytical thinking assistant. Provide structured, evidence-based insights.",
		},
		{
			Name:            "writer",
			Description:     "Writer template for content generation",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               false,
				AllowBrowser:             true,
				AllowBackgroundSubagents: false,
				MaxMemoryMB:              2048,
				MaxCPUFraction:           0.5,
				TimeoutSeconds:           600,
				MaxConcurrentTasks:       1,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule:      ScheduleConfig{Cron: "", HeartbeatInterval: 0, ActiveHours: nil, JitterSeconds: 0, Enabled: true},
			SystemPromptTemplate: "You are a writer tasked with producing clear, compelling content based on input prompts.",
		},
		{
			Name:            "browser-bot",
			Description:     "Browser automation helper",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               false,
				AllowBrowser:             true,
				AllowBackgroundSubagents: true,
				MaxMemoryMB:              4096,
				MaxCPUFraction:           0.7,
				TimeoutSeconds:           600,
				MaxConcurrentTasks:       2,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule:      ScheduleConfig{Cron: "", HeartbeatInterval: 0, ActiveHours: nil, JitterSeconds: 0, Enabled: true},
			SystemPromptTemplate: "You control a headless browser and perform automated browsing tasks as requested.",
		},
		{
			Name:            "monitor",
			Description:     "System monitor and health reporter",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               false,
				AllowBrowser:             false,
				AllowBackgroundSubagents: true,
				MaxMemoryMB:              1024,
				MaxCPUFraction:           0.3,
				TimeoutSeconds:           300,
				MaxConcurrentTasks:       1,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule:      ScheduleConfig{Cron: "", HeartbeatInterval: 0, ActiveHours: nil, JitterSeconds: 0, Enabled: true},
			SystemPromptTemplate: "You monitor system metrics and report anomalies with concise summaries.",
		},
		{
			Name:            "summarizer",
			Description:     "Summarization helper for long content",
			DefaultProvider: "openai",
			DefaultModel:    "gpt-4o",
			DefaultPolicy: PolicyConfig{
				AllowShell:               false,
				AllowBrowser:             false,
				AllowBackgroundSubagents: false,
				MaxMemoryMB:              2048,
				MaxCPUFraction:           0.4,
				TimeoutSeconds:           600,
				MaxConcurrentTasks:       1,
				NetworkMode:              "restricted",
				FilesystemMode:           "read-write",
			},
			DefaultSchedule:      ScheduleConfig{Cron: "", HeartbeatInterval: 0, ActiveHours: nil, JitterSeconds: 0, Enabled: true},
			SystemPromptTemplate: "You summarize provided content into concise bullets and key takeaways.",
		},
	}
	return tmpl
}
